# Generated by Django 3.0.4 on 2020-07-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('aurthor', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
