# Generated by Django 3.0.4 on 2020-07-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contact_issue', models.TextField()),
            ],
        ),
    ]
