# Generated by Django 3.0.4 on 2020-07-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_us_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='time',
        ),
    ]
